# Generated by Django 4.1.3 on 2022-12-01 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name': 'Entrada', 'verbose_name_plural': 'Entradas'},
        ),
    ]
