# Generated by Django 4.1.3 on 2022-12-07 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_autor_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='salary',
            field=models.IntegerField(verbose_name='Sueldo'),
        ),
    ]
