# Generated by Django 4.1.3 on 2022-12-27 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_director_alter_entry_author_entry_director'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='director',
            options={'verbose_name': 'Director', 'verbose_name_plural': 'Directores'},
        ),
        migrations.AddField(
            model_name='entry',
            name='image',
            field=models.ImageField(null=True, upload_to='Entry', verbose_name='Imagen'),
        ),
    ]
