# Generated by Django 4.1.3 on 2022-12-29 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_director_options_entry_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='entradas'),
        ),
    ]
