# Generated by Django 4.1.3 on 2022-12-29 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_author_date_birth_alter_entry_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='resume',
            field=models.TextField(null=True, verbose_name='resume'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='text',
            field=models.TextField(verbose_name='text'),
        ),
    ]
