# Generated by Django 4.1.3 on 2022-12-29 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_entry_resume_alter_entry_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='slug',
            field=models.SlugField(editable=False, max_length=100, null=True),
        ),
    ]
